algoritmo " Calculoidade"
var
   ano, nasc, idade : inteiro

inicio
      Escreva ("Em que ano estamos? ")
      Leia (ano)
      Escreva ("em que ano voce nasceu? ")
      Leia(nasc)
      idade<-ano - nasc
      Escreva ("Em " , ano, " voce tera " , idade, " anos ")
      Se (idade>= 21) entao
         EscrevaL(" e ja tera atingido a maioridade")
      Senao (idade<=21) entao
         EscrevaL (" voce ainda nao atingiu a maioridade")

         Fimse

      

      
      
fimalgoritmo
